services:
  automate-metashape:
    image: ghcr.io/open-forest-observatory/automate-metashape
    container_name: automate-metashape
    volumes:
      - ".:/data" # Mount the present working directory into the container
    environment:
      - AGISOFT_FLS=${AGISOFT_FLS} # Pass environment variable to the container
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  untwine:
    image: jeffgillan/cog_copc_generate:amd64
    container_name: cog_copc_generate
    depends_on:
      automate-metashape:
        condition: service_completed_successfully
    volumes:
      - ./output:/input
